name = "a2htray"
avatar = "images/profile.jpg"
bio = "Gopher and Student"
# company = 'Company'
# company = '<a href="https://example.com" target="_blank" rel="noopener noreferrer">Company</a>'
# location = "Earth"
# alternatives:
# location = "<a href='https://www.openstreetmap.org/search?query=Earth'>Earth</a>"
# location = "<a href='https://www.google.com/maps/search/Earth'>Earth</a>"
# about = "https://domain.tld" # The external about page. The internal about page will be used if not set.

[params]
  layout = "compact"

[social]
  email = "a2htray@outlook.com"
  github = "a2htray"
